### ISSUE TITLE
install bug within offical python 3.11-slim docker

### ISSUE THREAD

**Issue by ZoidbergPi** [yuz0101/aioTrends#3]
**Describe the bug**
root@2ddce338d671:/# python3.11 -m pip install aioTrends
Collecting aioTrends
  Using cached aioTrends-0.0.3.tar.gz (327 kB)
ERROR: aioTrends from https://files.pythonhosted.org/packages/68/12/57a9cffe972a4587fe399907eb2f764c218f99b0795f349c14e9627aa42c/aioTrends-0.0.3.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**To Reproduce**
1.  docker run -d  python:3.11-slim sleep 999999999 
2.  docker exec -it 2ddce338d671 bash
3. pip install --upgrade pip
4.  pip install aioTrends

**Expected behavior**
install

**Comment by yuz0101** [comment]
hi there, the setup file was put in the inappropriate folder, I fixed that. could you please try that again? appreciate your time.

**Comment by ZoidbergPi** [comment]
> 4\. pip install aioTrends

the problem still here:

ERROR: aioTrends from https://files.pythonhosted.org/packages/6d/38/d832a971cd304421352aedda5baaf1fffc29e3b9058c401ae90df0c99cf5/aioTrends-0.0.4.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.

**Comment by yuz0101** [comment]
hi, it works well on my end (see pic).

![image](https://github.com/yuz0101/aioTrends/assets/103857222/a6bd84e8-d2c4-4a14-b286-e2dcdeb81a21)

Could you please try below?

(1) uninstall the package and reinstall it.
or  
(2) try setup a new virtual environment and install it

I hope it is helpful to you.
